"""FastAPI routes for async video answer transcription."""

from __future__ import annotations

from typing import Annotated

import structlog
from fastapi import APIRouter, File, Form, UploadFile

router = APIRouter(prefix="/video", tags=["video"])
logger = structlog.get_logger()


@router.post("/transcribe")
async def transcribe_video(
    object_name: Annotated[str, Form(...)],
    video: Annotated[UploadFile, File(...)],
) -> dict[str, str]:
    """Return a deterministic mock transcript for a video answer.

    In production this routes to a real STT adapter behind the same port.
    The endpoint exists so the async video interview flow can be end-to-end
    tested without provider credentials.
    """
    content = await video.read()
    logger.info(
        "transcribe_video",
        object_name=object_name,
        filename=video.filename,
        content_type=video.content_type,
        size_bytes=len(content),
    )
    transcript = (
        "This is a placeholder transcript generated by the mock transcription adapter. "
        "The candidate discussed their relevant experience and provided concrete examples."
    )
    return {"transcript": transcript}
